### ISSUE TITLE
Picking a Color Palette 

### ISSUE THREAD

**Issue by EmilyDev** [jakepeyser/therapy#2]
As a user I want my app to have a nice color palette

**Comment by jakepeyser** [comment]
Color Palette: http://www.color-hex.com/color-palette/1294
- **Background**: #F8F8F8
- **Toolbar/Tabs**: #011F4B
- **Primary Button**: #005B96
- **Secondary Button/Badges**: #8D5300
- **Disabled Button**: #B3CDE0
- **Input Placeholder Text**: #8C8C8C
- **Active Input Labels**: #005B96
- **Error Text/Labels**: #D9534F
- **Text (Dark background)**: #FFFFFF
- **Text (Light background)**: #000000

**Comment by jakepeyser** [comment]
FYI @Hitenp1

**Comment by jakepeyser** [comment]
[Saved here in Google Docs](https://docs.google.com/document/d/1GIZ_aiurHFe0PnjRNW_3PSthTIdLjKV6C0LG_RuK93Y/edit?usp=sharing)
