### ISSUE TITLE
Home page Sketch

### ISSUE THREAD

**Issue by EmilyDev** [jakepeyser/therapy#9]
First page people hit.

**Comment by jakepeyser** [comment]
Initial Sketch. Color palette, text, and copy still need work...
![image](https://cloud.githubusercontent.com/assets/1534503/20370026/5351fd12-ac2a-11e6-88a6-d970b2122770.png)

**Comment by jakepeyser** [comment]
New background: https://static.pexels.com/photos/24746/pexels-photo-24746.jpg

- Add [saturation](http://www.w3schools.com/cssref/css3_pr_filter.asp) of 150% to the image

**Comment by jakepeyser** [comment]
### Log In
![image](https://cloud.githubusercontent.com/assets/1534503/20410579/cd8d40ac-aceb-11e6-8b0f-35bc2921b0a6.png)

### Sign Up
![image](https://cloud.githubusercontent.com/assets/1534503/20410596/ddf51244-aceb-11e6-99e6-15bde34eab55.png)

**Comment by jakepeyser** [comment]
[Sketch file uploaded to Google Docs](https://drive.google.com/file/d/0B74g2zDubN9jdjRuek1VYUZ6WG8/view?usp=sharing). Will version control the file from here
